const { UNUSED_COMPOSER_DEPENDENCIES, BUNDLE_IGNORE, GIT_IGNORE, NPM_IGNORE } = require( './constants' );

module.exports = {
    UNUSED_COMPOSER_DEPENDENCIES,
    BUNDLE_IGNORE,
    GIT_IGNORE,
    NPM_IGNORE,
};